### ISSUE TITLE
Unable to use via Node

### ISSUE THREAD

**Issue by domness** [HenrikJoreteg/SimpleWebRTC#212]
After using the node package for SimpleWebRTC, I'm unable to build due to Hark trying to access window:

```
/Users/Mac/Code/Node/react-chat-app/node_modules/webrtc/node_modules/localmedia/node_modules/hark/hark.js:17
var audioContextType = window.AudioContext || window.webkitAudioContext;
                       ^
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/Mac/Code/Node/react-chat-app/node_modules/webrtc/node_modules/localmedia/node_modules/hark/hark.js:17:24)
    at Module._compile (module.js:456:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Mac/Code/Node/react-chat-app/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Mac/Code/Node/react-chat-app/node_modules/webrtc/node_modules/localmedia/index.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Mac/Code/Node/react-chat-app/node_modules/node-jsx/index.js:26:12)
```

**Comment by fippo** [comment]
well, you don't have MediaStreams in node? Nor other parts of WebRTC?

**Comment by domness** [comment]
My bad, I was trying to deploy an app today and had some wrong values (It's a React app). Working fine now.

**Comment by pravindodia** [comment]
@domness  Can you help me how did you fix this error ? Trying since long and getting no clue other than this post, nor do i understand the comment you have made. Sorry but kinda rookie on this.
